arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
    - joint_left
    - joint_right
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
